### ISSUE TITLE
Wrong guid

### ISSUE THREAD

**Issue by rhuijben** [FatalSleep/Sharp-IPC#1]
The guid used for the single instance mutex, has a well known issue. The call to GetType() should be removed, or the guid of one of the common .net assemblies is used.

Several blog posts were written about this issue, as this code was copy and pasted over the web many times.

**Comment by Yaazarai** [comment]
Fixed. You cannot use common .NET assemblies because you don't want your process using GUIDs commonly accessible to other programs in the .NET environment. Doubt it'd ever be an issue, but with that in mind I have used an appropriate replacement for the GetType() method.
